### PR TITLE
Update bitflags to 0.7

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by nox** [comment]
bitflags 0.6 and 0.7 are not compatible with Rust <1.8, maybe I should use a version range there?

**Comment by elinorbgr** [comment]
If they are API compatible (at least for the part used by wayland-kbd) it'd be best, yes.

**Comment by nox** [comment]
0.5-0.7 are. Will amend the patch soon.

**Comment by nox** [comment]
Amended!

**Comment by elinorbgr** [comment]
Thanks!

**Pull request merged**
