### PR TITLE
Update to bitflags 0.3.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by elinorbgr** [comment]
I'm not sure I understand why the build failed like this, looks like there is some nasty thing going on...

I'll look a little into this, however be aware that this library is going to be radically changed in the near future, to follow the complete changes of `wayland-client-0.3`. I'll probably see to update the dependencies then.

Unless there is a really urgent need to update this dependency ?

**Comment by Ms2ger** [comment]
Not really; I just noticed that Servo depends on two versions of bitflags, which is annoying but not problematic.

**Comment by elinorbgr** [comment]
Well, if servo depends on wayland-kdb through glutin, it'll eventually get fixed.

I'm in the middle of a big overhaul of my wayland-\* crates in conjunction with some changes from the wayland devs, in order to make the whole thing more rusty. But it takes some time to get all things updated.

**Comment by elinorbgr** [comment]
Alright, these were just some issues with the dev_dependencies, fixed now!

Thanks!

**Pull request merged**
